### ISSUE TITLE
This convolution is not supported by cudnn, MXNET convolution is applied.

### ISSUE THREAD

**Issue by TerryLovesLife** [msracver/Deep-Feature-Flow#16]
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
[19:15:03] src/operator/convolution.cu:87: This convolution is not supported by cudnn, MXNET convolution is applied.
Traceback (most recent call last):
  File "experiments/dff_rfcn/dff_rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/dff_rfcn/../../dff_rfcn/train_end2end.py", line 171, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/dff_rfcn/../../dff_rfcn/train_end2end.py", line 164, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "experiments/dff_rfcn/../../dff_rfcn/core/module.py", line 969, in fit
    self.update()
  File "experiments/dff_rfcn/../../dff_rfcn/core/module.py", line 1051, in update
    self._curr_module.update()
  File "experiments/dff_rfcn/../../dff_rfcn/core/module.py", line 572, in update
    self._kvstore)
TypeError: _update_params_on_kvstore() takes exactly 4 arguments (3 given)

-------------------------------------------Error log  above ------------------------------------------------

When  I use DFF + R-FCN to train the imagenet dataset, DET+VID, it keep waing that "This convolution is not supported by cudnn, MXNET convolution is applied." and then error occur, is it because  I am using Mxnet 0.10.0 release ?

Thank you.

**Comment by Orpine** [comment]
Please add 'cudnn_off=True' to all Conv op with dilate != 1. You could refer the symbols in Deformable ConvNets

**Comment by TerryLovesLife** [comment]
Problem solved with your provided solution,Thank you!

**Comment by weilanShi** [comment]
> Problem solved with your provided solution,Thank you!

How did you solve this problem? I also met this problem.

**Comment by weilanShi** [comment]
> Please add 'cudnn_off=True' to all Conv op with dilate != 1. You could refer the symbols in Deformable ConvNets

Can you be more specific? I also have this problem, but it has not been solved yet. Thank you.
