### ISSUE TITLE
errors run with demo

### ISSUE THREAD

**Issue by huanhuanxuxu** [msracver/Deep-Feature-Flow#18]
hi,
I'm running the demo and here is the error I encountered:
`[10:46:34] /home/huan/Deep-Feature-Flow/mxnet/dmlc-core/include/dmlc/./logging.h:300: [10:46:34] src/c_api/c_api_ndarray.cc:390: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f0d5982bf9c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(MXImperativeInvoke+0x8d1) [0x7f0d5a3d4cb1]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f0d4c88ce40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f0d4c88c8ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f0d4ca9c3df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f0d4caa0d82]
[bt] (6) /usr/bin/python2.7(PyObject_Call+0x43) [0x4b0cb3]
[bt] (7) /usr/bin/python2.7(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (8) /usr/bin/python2.7(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (9) /usr/bin/python2.7(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]

Traceback (most recent call last):
  File "./dff_rfcn/demo_batch.py", line 162, in <module>
    main()
  File "./dff_rfcn/demo_batch.py", line 111, in main
    arg_params=arg_params, aux_params=aux_params)
  File "/home/huan/Deep-Feature-Flow/dff_rfcn/core/tester.py", line 30, in __init__
    self._mod.bind(provide_data, provide_label, for_training=False)
  File "/home/huan/Deep-Feature-Flow/dff_rfcn/core/module.py", line 839, in bind
    for_training, inputs_need_grad, force_rebind=False, shared_module=None)
  File "/home/huan/Deep-Feature-Flow/dff_rfcn/core/module.py", line 396, in bind
    state_names=self._state_names)
  File "/home/huan/Deep-Feature-Flow/dff_rfcn/core/DataParallelExecutorGroup.py", line 186, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/huan/Deep-Feature-Flow/dff_rfcn/core/DataParallelExecutorGroup.py", line 272, in bind_exec
    shared_group))
  File "/home/huan/Deep-Feature-Flow/dff_rfcn/core/DataParallelExecutorGroup.py", line 545, in _bind_ith_exec
    context, self.logger)
  File "/home/huan/Deep-Feature-Flow/dff_rfcn/core/DataParallelExecutorGroup.py", line 523, in _get_or_reshape
    arg_arr = nd.zeros(arg_shape, context, dtype=arg_type)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/ndarray.py", line 946, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/_ctypes/ndarray.py", line 164, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(val) for val in vals])))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:46:34] src/c_api/c_api_ndarray.cc:390: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 10 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f0d5982bf9c]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/libmxnet.so(MXImperativeInvoke+0x8d1) [0x7f0d5a3d4cb1]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7f0d4c88ce40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7f0d4c88c8ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7f0d4ca9c3df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7f0d4caa0d82]
[bt] (6) /usr/bin/python2.7(PyObject_Call+0x43) [0x4b0cb3]
[bt] (7) /usr/bin/python2.7(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (8) /usr/bin/python2.7(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (9) /usr/bin/python2.7(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]`

so is it the problem of mxnet install?

**Comment by huanhuanxuxu** [comment]
aha, it turns out the problem is I did not compile mxnet with cuda, for those have same errors, turn USE_CUDA = 1 recompile alles OK.

**Comment by einsiedler0408** [comment]
solved
