### ISSUE TITLE
ERROR on DEMO(undefined symbol: PyFPE_jbuf ) and question

### ISSUE THREAD

**Issue by seongkyun** [msracver/Deep-Feature-Flow#22]
i ran this code on my pc.

but after installation of Anaconda2, i does not works.

several errors were occurred but i solved it(like GOMP4.0 or gcc errors)

and finally i ran this code on my ubuntu 16.04 with Anaconda2,

i met this error codes

`name@name:~/Deep-Feature-Flow/rfcn$ python ./demo.py `

`Traceback (most recent call last):
  File "./demo.py", line 29, in <module>
    from core.tester import im_detect, Predictor
  File "/home/han/Deep-Feature-Flow/rfcn/core/tester.py", line 18, in <module>
    from nms.nms import py_nms_wrapper, cpu_nms_wrapper, gpu_nms_wrapper
  File "/home/han/Deep-Feature-Flow/rfcn/../lib/nms/nms.py", line 3, in <module>
    from cpu_nms import cpu_nms
ImportError: /home/han/Deep-Feature-Flow/rfcn/../lib/nms/cpu_nms.so: undefined symbol: PyFPE_jbuf`

what is this error code??? how could i fix it?

and there is another question.

what is difference between **rfcn** with **dff_rfcn** ???

can you please explain it??

because rfcn is better than dff_rfcn for my dataset.

I think that rfcn is not Deep-Feature-Flow one and dff_rfcn is applied Deep-Feature-Flow paper.

Is that right?

Answer me plz dear friends :)

**Comment by einsiedler0408** [comment]
Did you run sh ./init.sh. The scripts will build cython module automatically and create some folders.

rfcn is from R-FCN: Object Detection via Region-based Fully Convolutional Networks, which is an image object detector.
dff_rfcn is from our Deep-Feature-Flow paper, which uses R-FCN as object detector.

**Comment by dljrichard** [comment]
> i ran this code on my pc.
> 
> but after installation of Anaconda2, i does not works.
> 
> several errors were occurred but i solved it(like GOMP4.0 or gcc errors)
> 
> and finally i ran this code on my ubuntu 16.04 with Anaconda2,
> 
> i met this error codes
> 
> `name@name:~/Deep-Feature-Flow/rfcn$ python ./demo.py `
> 
> `Traceback (most recent call last): File "./demo.py", line 29, in <module> from core.tester import im_detect, Predictor File "/home/han/Deep-Feature-Flow/rfcn/core/tester.py", line 18, in <module> from nms.nms import py_nms_wrapper, cpu_nms_wrapper, gpu_nms_wrapper File "/home/han/Deep-Feature-Flow/rfcn/../lib/nms/nms.py", line 3, in <module> from cpu_nms import cpu_nms ImportError: /home/han/Deep-Feature-Flow/rfcn/../lib/nms/cpu_nms.so: undefined symbol: PyFPE_jbuf`
> 
> what is this error code??? how could i fix it?
> 
> and there is another question.
> 
> what is difference between **rfcn** with **dff_rfcn** ???
> 
> can you please explain it??
> 
> because rfcn is better than dff_rfcn for my dataset.
> 
> I think that rfcn is not Deep-Feature-Flow one and dff_rfcn is applied Deep-Feature-Flow paper.
> 
> Is that right?
> 
> Answer me plz dear friends :)

facing the same problem. Have you solved it?
