### ISSUE TITLE
Shape error occur when running the experiment

### ISSUE THREAD

**Issue by yljylj** [msracver/Deep-Feature-Flow#32]
[09:38:23] /home/pdl/workspace2/ylj/MXNet/mxnet/dmlc-core/include/dmlc/logging.h:308: [09:38:23] src/operator/batch_norm-inl.h:238: Check failed: channelAxis < dshape.ndim() (1 vs. 0) Channel axis out of range: 1
Stack trace returned 10 entries:
[bt] (0) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fd8fec99aac]
[bt] (1) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op13BatchNormProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x979) [0x7fd8ffbab989]
[bt] (2) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(+0x16979e7) [0x7fd8ffb719e7]
[bt] (3) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(+0x152be47) [0x7fd8ffa05e47]
[bt] (4) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet4exec10InferShapeEN4nnvm5GraphESt6vectorINS1_6TShapeESaIS4_EERKSs+0x83b) [0x7fd8ffa07afb]
[bt] (5) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0x17ed) [0x7fd8ff99f62d]
[bt] (6) /home/pdl/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c) [0x7fd90e97857c]
[bt] (7) /home/pdl/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5) [0x7fd90e977cd5]
[bt] (8) /home/pdl/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6) [0x7fd90e96f376]
[bt] (9) /home/pdl/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(+0x9db3) [0x7fd90e966db3]

infer_shape error. Arguments:
  data: (1L, 3L, 562L, 1000L)
  label: (1L, 20412L)
  bbox_target: (1L, 36L, 36L, 63L)
  bbox_weight: (1L, 36L, 36L, 63L)
Traceback (most recent call last):
  File "dff_rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "../../dff_rfcn/train_end2end.py", line 182, in main
    config['TRAIN']['begin_epoch'], config['TRAIN']['end_epoch'], config['TRAIN']['lr'], config['TRAIN']['lr_step'])
  File "../../dff_rfcn/train_end2end.py", line 101, in train_net
    sym_instance.infer_shape(data_shape_dict)
  File "../../dff_rfcn/../lib/utils/symbol.py", line 38, in infer_shape
    arg_shape, out_shape, aux_shape = self.sym.infer_shape(**data_shape_dict)
  File "/home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/symbol/symbol.py", line 958, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/symbol/symbol.py", line 1087, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/base.py", line 143, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator bn_conv1: [09:38:23] src/operator/batch_norm-inl.h:238: Check failed: channelAxis < dshape.ndim() (1 vs. 0) Channel axis out of range: 1

Stack trace returned 10 entries:
[bt] (0) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7fd8fec99aac]
[bt] (1) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(_ZNK5mxnet2op13BatchNormProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x979) [0x7fd8ffbab989]
[bt] (2) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(+0x16979e7) [0x7fd8ffb719e7]
[bt] (3) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(+0x152be47) [0x7fd8ffa05e47]
[bt] (4) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(_ZN5mxnet4exec10InferShapeEN4nnvm5GraphESt6vectorINS1_6TShapeESaIS4_EERKSs+0x83b) [0x7fd8ffa07afb]
[bt] (5) /home/pdl/workspace2/ylj/MXNet/mxnet/python/mxnet/../../lib/libmxnet.so(MXSymbolInferShape+0x17ed) [0x7fd8ff99f62d]
[bt] (6) /home/pdl/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c) [0x7fd90e97857c]
[bt] (7) /home/pdl/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5) [0x7fd90e977cd5]
[bt] (8) /home/pdl/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6) [0x7fd90e96f376]
[bt] (9) /home/pdl/anaconda2/lib/python2.7/lib-dynload/_ctypes.so(+0x9db3) [0x7fd90e966db3]

It seems like something wrong with the image shape， but I don't know how to solve it. Help， please！

**Comment by xuwentang** [comment]
hello , i don't download DET and VID, can you share it?thank you.

**Comment by mornfairy** [comment]
> hello , i don't download DET and VID, can you share it?thank you.
http://bvisionweb1.cs.unc.edu/ilsvrc2015/download-videos-3j16.php#vid
