### ISSUE TITLE
install problem...

### ISSUE THREAD

**Issue by amiltonwong** [msracver/Deep-Feature-Flow#4]
Hi, all,

After I followed the steps in readme, I came across the following error when executing `./init.sh`

```
(tf_1.0) root@milton-All-Series:/data/code/Deep-Feature-Flow# ./init.sh 
running build_ext
cythoning bbox.pyx to bbox.c
building 'bbox' extension
creating build
creating build/temp.linux-x86_64-3.5
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/root/anaconda3/envs/tf_1.0/lib/python3.5/site-packages/numpy/core/include -I/root/anaconda3/envs/tf_1.0/include/python3.5m -c bbox.c -o build/temp.linux-x86_64-3.5/bbox.o -Wno-cpp -Wno-unused-function
gcc -pthread -shared -L/root/anaconda3/envs/tf_1.0/lib -Wl,-rpath=/root/anaconda3/envs/tf_1.0/lib,--no-as-needed build/temp.linux-x86_64-3.5/bbox.o -L/root/anaconda3/envs/tf_1.0/lib -lpython3.5m -o /data/code/Deep-Feature-Flow/lib/bbox/bbox.cpython-35m-x86_64-linux-gnu.so
Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 51, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
(tf_1.0) root@milton-All-Series:/data/code/Deep-Feature-Flow#
```

Any suggestion to fix it?
I had installed:  MXNet@(commit 62ecb60)
and  Cython,  opencv-python==3.2.0.6, easydict==1.6  as required.

Thanks~

**Comment by AKSHAYUBHAT** [comment]
Use python 2.x 
http://stackoverflow.com/questions/30418481/error-dict-object-has-no-attribute-iteritems-when-trying-to-use-networkx

**Comment by amiltonwong** [comment]
Thanks, after switching back to py 2.7.x, it works
