### ISSUE TITLE
Error when running end2end training test 

### ISSUE THREAD

**Issue by VasilisGks** [msracver/Deep-Feature-Flow#46]
Hi , when i run the project i get the following error: 

wrote gt roidb to ./data/cache/ImageNetVID_VID_train_15frames_gt_roidb.pkl
append flipped images to roidb
filtered 3316 roidb entries: 222946 -> 219630
Traceback (most recent call last):
  File "experiments/dff_rfcn/dff_rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/dff_rfcn/../../dff_rfcn/train_end2end.py", line 171, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/dff_rfcn/../../dff_rfcn/train_end2end.py", line 83, in train_net
    bbox_std=config.network.ANCHOR_STDS)
  File "experiments/dff_rfcn/../../dff_rfcn/core/loader.py", line 186, in __init__
    self.get_batch_individual()
  File "experiments/dff_rfcn/../../dff_rfcn/core/loader.py", line 336, in get_batch_individual
    rst.append(self.parfetch(iroidb))
  File "experiments/dff_rfcn/../../dff_rfcn/core/loader.py", line 344, in parfetch
    data, label = get_rpn_pair_batch(iroidb, self.cfg)
  File "experiments/dff_rfcn/../../dff_rfcn/../lib/rpn/rpn.py", line 72, in get_rpn_pair_batch
    imgs, ref_imgs, eq_flags, roidb = get_pair_image(roidb, cfg)
  File "experiments/dff_rfcn/../../dff_rfcn/../lib/utils/image.py", line 61, in get_pair_image
    assert os.path.exists(roi_rec['image']), '%s does not exist'.format(roi_rec['image'])
AssertionError: %s does not exist

Any idea what's going on?

**Comment by Jessespace** [comment]
Did you solve it?

**Comment by Javacr** [comment]
Dear Jessespace，could you please help me! I want to train 2-label dataset, but I don’t know how to change the program. My email address: ww.zhipeng@gmail.com
