### ISSUE TITLE
install problem

### ISSUE THREAD

**Issue by Troy922** [msracver/Deep-Feature-Flow#5]
hi,all
i want to try this algrithm on virtual machine and my system is ubuntu 16.04.
I had installed: MXNet@(commit 62ecb60) and Cython, opencv-python==3.2.0.6, easydict==1.6 as required. My python version is 2.7.12. But i came across this problem when i run init.sh

Traceback (most recent call last):
  File "setup_linux.py", line 56, in <module>
    CUDA = locate_cuda()
  File "setup_linux.py", line 44, in locate_cuda
    raise EnvironmentError('The nvcc binary could not be '
EnvironmentError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set $CUDAHOME

how can i fix this problem? is it possible to run the demo on virtual machine?

**Comment by Orpine** [comment]
Our code require a GPU to run, please install cuda and I doubt that a VM can do this.

**Comment by liurongdev** [comment]
> Our code require a GPU to run, please install cuda and I doubt that a VM can do this.

老铁，我的代码跑到中间断了，百度mxnet版本有问题，修复之后怎么继续接着跑呢？
python experiments/dff_rfcn/dff_rfcn_end2end_train_test.py --cfg experiments/dff_rfcn/cfgs/resnet_v1_101_flownet_imagenet_vid_rfcn_end2end_ohem.yaml
正在跑这个代码
