### ISSUE TITLE
run error

### ISSUE THREAD

**Issue by Jessespace** [msracver/Deep-Feature-Flow#57]
When I run "**python experiments/dff_rfcn/dff_rfcn_end2end_train_test.py --cfg experiments/dff_rfcn/cfgs/resnet_v1_101_flownet_imagenet_vid_rfcn_end2end_ohem.yaml**", it generator **xxx.log** in **output/**,It was been running for a while, but occurred this problem:

`by cudnn, MXNET convolution is applied.
Traceback (most recent call last):
  File "experiments/dff_rfcn/dff_rfcn_end2end_train_test.py", line 19, in <module>
    train_end2end.main()
  File "experiments/dff_rfcn/../../dff_rfcn/train_end2end.py", line 171, in main
    config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step)
  File "experiments/dff_rfcn/../../dff_rfcn/train_end2end.py", line 164, in train_net
    arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "experiments/dff_rfcn/../../dff_rfcn/core/module.py", line 990, in fit
[14:22:42] src/operator/nn/convolution.cu:218: This convolution is not supported by cudnn, MXNET convolution is applied.
    self.set_params(arg_params, aux_params)
  File "/home/tsn/software/incubator-mxnet/python/mxnet/module/base_module.py", line 679, in set_params
    allow_extra=allow_extra)
TypeError: init_params() got an unexpected keyword argument 'allow_extra'`

How to fix this problem?  Thanks for your help!

**Comment by zhanglanqing** [comment]
may be this could help https://github.com/apache/incubator-mxnet/issues/8638
@Jessespace

**Comment by Roshrini** [comment]
@Jessespace Did removing "allow_extra" parameter help to solve the issue? [apache/incubator-mxnet#8638 ](https://github.com/apache/incubator-mxnet/issues/8638)

**Comment by weilanShi** [comment]
> When I run "**python experiments/dff_rfcn/dff_rfcn_end2end_train_test.py --cfg experiments/dff_rfcn/cfgs/resnet_v1_101_flownet_imagenet_vid_rfcn_end2end_ohem.yaml**", it generator **xxx.log** in **output/**,It was been running for a while, but occurred this problem:
> 
> `by cudnn, MXNET convolution is applied. Traceback (most recent call last): File "experiments/dff_rfcn/dff_rfcn_end2end_train_test.py", line 19, in <module> train_end2end.main() File "experiments/dff_rfcn/../../dff_rfcn/train_end2end.py", line 171, in main config.TRAIN.begin_epoch, config.TRAIN.end_epoch, config.TRAIN.lr, config.TRAIN.lr_step) File "experiments/dff_rfcn/../../dff_rfcn/train_end2end.py", line 164, in train_net arg_params=arg_params, aux_params=aux_params, begin_epoch=begin_epoch, num_epoch=end_epoch) File "experiments/dff_rfcn/../../dff_rfcn/core/module.py", line 990, in fit [14:22:42] src/operator/nn/convolution.cu:218: This convolution is not supported by cudnn, MXNET convolution is applied. self.set_params(arg_params, aux_params) File "/home/tsn/software/incubator-mxnet/python/mxnet/module/base_module.py", line 679, in set_params allow_extra=allow_extra) TypeError: init_params() got an unexpected keyword argument 'allow_extra'`
> 
> How to fix this problem? Thanks for your help!

How did you solve this problem? I also met this problem.

**Comment by weilanShi** [comment]
You can enter this directory： "/home/tsn/software/incubator-mxnet/python/mxnet/module/base_module.py", see the  line 679 : self.init_params(initializer=None, arg_params=arg_params, aux_params=aux_params,
                         allow_missing=allow_missing, force_init=force_init,
                         allow_extra=allow_extra)
and delete the ( allow_extra=allow_extra)
