### ISSUE TITLE
TypeError: '_Stat' object does not support indexing

### ISSUE THREAD

**Issue by FCInter** [msracver/Deep-Feature-Flow#73]
I'm running the code on a server. However, when I run the `init.sh`, I received the following error messages. What's wrong with the code?
I'm using python 2.7 and mxnet-1.2.1.

```
Traceback (most recent call last):
  File "setup_linux.py", line 92, in <module>
    cmdclass={'build_ext': custom_build_ext},
  File "/opt/conda/envs/python27_mxnet/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/opt/conda/envs/python27_mxnet/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/opt/conda/envs/python27_mxnet/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/opt/conda/envs/python27_mxnet/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/opt/conda/envs/python27_mxnet/lib/python2.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "setup_linux.py", line 74, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/envs/python27_mxnet/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 192, in build_extensions
    ext.sources = self.cython_sources(ext.sources, ext)
  File "/opt/conda/envs/python27_mxnet/lib/python2.7/site-packages/Cython/Distutils/old_build_ext.py", line 322, in cython_sources
    rebuild = self.force or newer_group(depends, target, 'newer')
  File "/opt/conda/envs/python27_mxnet/lib/python2.7/distutils/dep_util.py", line 75, in newer_group
    target_mtime = os.stat(target)[ST_MTIME]
TypeError: '_Stat' object does not support indexing
```

**Comment by Frag17** [comment]
I meet the same error with python3.6.5 when install sklearn, did you solved it?
